### PR TITLE
Switch header path from hpp to h for filter_base

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
**Problem Description**
For some reason, there seems to be a change in the header path extension. I am not sure if this is a change triggered from one of the dependencies, or if this package is working with a customized dependency somewhere. 

The build fails in the following systems
- Ubuntu 16.04 Xenial ROS Kinetic
- Ubuntu 18.04 Bionic ROS Melodic
- Ubuntu 20.04 Focal ROS Noetic
```
Errors     << grid_map_cv:make /home/jaeyoung/catkin_ws/logs/grid_map_cv/build.make.004.log                                                                                                                       
In file included from /home/jaeyoung/catkin_ws/src/grid_map/grid_map_cv/src/InpaintFilter.cpp:9:0:
/home/jaeyoung/catkin_ws/src/grid_map/grid_map_cv/include/grid_map_cv/InpaintFilter.hpp:11:10: fatal error: filters/filter_base.hpp: No such file or directory
 #include <filters/filter_base.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/grid_map_cv.dir/src/InpaintFilter.cpp.o] Error 1
make[1]: *** [CMakeFiles/grid_map_cv.dir/all] Error 2
make: *** [all] Error 2
cd /home/jaeyoung/catkin_ws/build/grid_map_cv; catkin build --get-env grid_map_cv | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
..................................................................................................................................................................................................................
Failed     << grid_map_cv:make                      [ Exited with code 2 ]                                                                                                                                        
Failed    <<< grid_map_cv                           [ 0.3 seconds ]                                                                                                                                               
Abandoned <<< grid_map_ros                          [ Unrelated job failed ]                                                                                                                                      
Abandoned <<< grid_map_filters                      [ Unrelated job failed ]                                                                                                                                      
Abandoned <<< grid_map_loader                       [ Unrelated job failed ]                                                                                                                                      
Abandoned <<< grid_map_rviz_plugin                  [ Unrelated job failed ]                                                                                                                                      
Abandoned <<< grid_map_visualization                [ Unrelated job failed ]                                                                                                                                      
Abandoned <<< grid_map_demos                        [ Unrelated job failed ]                                                                                                                                      
[build] Summary: 3 of 10 packages succeeded.                                                                                                                                                                      
[build]   Ignored:   59 packages were skipped or are blacklisted.                                                                                                                                                 
[build]   Warnings:  None.                                                                                                                                                                                        
[build]   Abandoned: 6 packages were abandoned.                                                                                                                                                                   
[build]   Failed:    1 packages failed.                                                                                                                                                                           
[build] Runtime: 0.9 seconds total.                             
```

**Solution**
Siwtch header path extension from `filters.hpp` to `filters.h`

**Additional Context**
- This has also been reported in https://github.com/ANYbotics/grid_map/issues/292, https://github.com/ANYbotics/grid_map/issues/295

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
CI failures seem to be unrelated to this PR
image

**Comment by maximilianwulf** [comment]
Thank you for the MR, we will look into it.

**Comment by maximilianwulf** [comment]
Could you target your MR upon this branch? https://github.com/ANYbotics/grid_map/tree/melodic-devel

**Comment by Jaeyoung-Lim** [comment]
> Could you target your MR upon this branch? https://github.com/ANYbotics/grid_map/tree/melodic-devel

Done in https://github.com/ANYbotics/grid_map/pull/304

**Comment by maximilianwulf** [comment]
Thank you.

**Pull request closed without merging**
