### PR TITLE
Fix for clang build

### PR DESCRIPTION
**Pull request by kenji-miyake**
As I found this repository can't be built with `clang++`, I fixed errors.

### How to reproduce the problem.

```sh
git clone git@github.com:ANYbotics/grid_map.git -b ros2
cd grid_map
CXX=clang++ colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
```

### CODE REVIEW

**Comment by kenji-miyake** [comment]
Rebased on #321.

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Its a draft so I can't merge it until you set up to be a full PR

**Comment by SteveMacenski** [comment]
Retriggered build, failure was not your fault, this is a big project so we're reaching the memory limit sometimes while building. Let me know when it passes.

**Comment by kenji-miyake** [comment]
@SteveMacenski Ummm...? What should/can I do?
Are you saying I should retrigger CI until it randomly passes?

If so, I re-recommend switching to GitHub Actions(https://github.com/ANYbotics/grid_map/pull/320), which seems to have 7GB RAM while Circle CI has 4GB.
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

I guess you're concerned about the learning cost, but it's very similar to Circle CI's grammar and easy to use.

**Comment by wep21** [comment]
@kenji-miyake https://github.com/ANYbotics/grid_map/pull/332 has been merged, so could you close this PR?

**Comment by kenji-miyake** [comment]
@wep21 Sure. Thank you!

**Pull request closed without merging**
