### PR TITLE
melodic compatibility

### PR DESCRIPTION
**Pull request by ipa-jba**
thanks to @flbeck for the fixed rviz plugin

### CODE REVIEW

**Comment by Axel13fr** [comment]
Hi Gents, waiting for this to migrate to melodic :-) Could you review it so we can get debian pkg release as well ?

**Comment by JWhitleyAStuff** [comment]
@pfankhauser - Any update on the Melodic release status? This is currently the last requirement holding for Melodic release on https://github.com/CPFL/Autoware/issues/1697

**Comment by pfankhauser** [comment]
We are working on this [here](#200), will be provided as packages asap.

**Comment by samuelba** [comment]
I did the release for melodic: https://github.com/ros/rosdistro/pull/20399

I guess we can close this?

**Comment by pfankhauser** [comment]
Great, thanks @samuelba, @MarcoSuetterlin & @remod!

**Pull request closed without merging**
