### PR TITLE
Fixed crash when switching from a topic that doesn't publish

### PR DESCRIPTION
**Pull request by StefanFabian**
See #210

### CODE REVIEW

**Comment by StefanFabian** [comment]
Push since I just noticed this PR still exists ^^

**Comment by maximilianwulf** [comment]
Thank it is imported :)

**Comment by StefanFabian** [comment]
Then I assume we can close this?

**Comment by maximilianwulf** [comment]
Yes, once its on this repository. Thank you for the fix :)

**Comment by Magnusgaertner** [comment]
Changes have been long integrated.

**Pull request closed without merging**
