### PR TITLE
[Noetic] Add compatibility for ROS noetic (no message change)

### PR DESCRIPTION
**Pull request by RaphvK**
This pull request is forked from #231. 

The necessary adaptions for compilation on ROS Noetic in GridMapVisual.cpp and CMakelists.txt were kept, but all changes regarding the change of the GridMap message (moving the header from GridMapInfo to GridMap) were reverted.

Instead, the modified frame_manager.h was recreated based upon the frame_manager.h coming with the ROS Noetic release of rviz. Thus, support for tf was dropped, only tf2 is supported.

### CODE REVIEW

**Comment by maximilianwulf** [comment]
Hey @RaphvK , thanks for the PR, is the current version not working for you on Noetic? 

I will double check internally, but I think grid_map should work on Noetic now.

**Comment by RaphvK** [comment]
Hi @maximilianwulf ,

thank you for your feedback. 

I cloned the current master again to double-check whether it is working now. But I am still getting the following error when compiling. I suspected that it comes from a change in the FrameManager in ROS Noetic and therefore used the `frame_manager.h` coming with ROS Noetic and modified it to use the header in `GridMapInfo` in this pull request.

```
Errors     << grid_map_rviz_plugin:make /home/rosuser/unicaragil-cloud/ros/logs/grid_map_rviz_plugin/build.make.001.log                                               
In file included from /opt/ros/noetic/include/rviz/message_filter_display.h:37,
                 from /home/ros/src/dependencies/grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/message_filter_display.h:13,
                 from /home/ros/build/grid_map_rviz_plugin/include/grid_map_rviz_plugin/../../../../src/dependencies/grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/GridMapDisplay.hpp:15,
                 from /home/ros/build/grid_map_rviz_plugin/include/grid_map_rviz_plugin/moc_GridMapDisplay.cpp:9:
/opt/ros/noetic/include/rviz/display_context.h: In member function ‘std::shared_ptr<tf2_ros::Buffer> rviz::DisplayContext::getTF2BufferPtr() const’:
/opt/ros/noetic/include/rviz/display_context.h:100:31: error: ‘class rviz::FrameManager’ has no member named ‘getTF2BufferPtr’
  100 |     return getFrameManager()->getTF2BufferPtr();
      |                               ^~~~~~~~~~~~~~~
In file included from /opt/ros/noetic/include/rviz/message_filter_display.h:37,
                 from /home/ros/src/dependencies/grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/modified/message_filter_display.h:13,
                 from /home/ros/src/dependencies/grid_map/grid_map_rviz_plugin/include/grid_map_rviz_plugin/GridMapDisplay.hpp:15,
                 from /home/ros/src/dependencies/grid_map/grid_map_rviz_plugin/src/GridMapDisplay.cpp:10:
/opt/ros/noetic/include/rviz/display_context.h: In member function ‘std::shared_ptr<tf2_ros::Buffer> rviz::DisplayContext::getTF2BufferPtr() const’:
/opt/ros/noetic/include/rviz/display_context.h:100:31: error: ‘class rviz::FrameManager’ has no member named ‘getTF2BufferPtr’
  100 |     return getFrameManager()->getTF2BufferPtr();
      |                               ^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/grid_map_rviz_plugin.dir/build.make:106: CMakeFiles/grid_map_rviz_plugin.dir/include/grid_map_rviz_plugin/moc_GridMapDisplay.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/grid_map_rviz_plugin.dir/build.make:80: CMakeFiles/grid_map_rviz_plugin.dir/src/GridMapDisplay.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:341: CMakeFiles/grid_map_rviz_plugin.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /home/ros/build/grid_map_rviz_plugin; catkin build --get-env grid_map_rviz_plugin | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -
......................................................................................................................................................................
```

**Comment by maximilianwulf** [comment]
Hey @RaphvK, I am sorry, we did not yet publish our grid map noetic release. I guess it will be coming any day soon. I hope you can live with that.

**Comment by RaphvK** [comment]
Sure, that's fine. Looking forward to seeing it released 👍

**Comment by maximilianwulf** [comment]
Hey @RaphvK, grid_map should work on Noetic, will close this PR accordingly. 

Thank you for your proposal :)

**Pull request closed without merging**
