### PR TITLE
build: treat several build issues on rolling 

### PR DESCRIPTION
**Pull request by wep21**
- skip installing octomap server because it is still not available on rolling.
- ignore compiler warnings due to gcc 13 bug

### CODE REVIEW

**Comment by Ryanf55** [comment]
Looks like some new compile errors are cropping up in rolling.
https://github.com/ANYbotics/grid_map/actions/runs/9212196119/job/25343302006?pr=458#step:6:40

Do you think you would have time to get those fixed so CI passes too, or not?

**Comment by wep21** [comment]
I adopted the change from [this PR](https://github.com/ros2/rosidl/pull/803) to suppress compiler warning due to gcc13 bug.

**Comment by wep21** [comment]
I cherry-picked [the change](https://github.com/ANYbotics/grid_map/pull/456/commits/21f3bc53a07e6e623d95975257195b9865c1c7f0) to check if rolling ci passes.

**Comment by Ryanf55** [comment]
Nice find. Looks like theres more issues. Were you hoping to merge as-is and fix the rest later? I don't yet have a jazzy environment configured yet.

**Comment by wep21** [comment]
Additionally, I added 2 changes as below.
- change nav2 repo temporarily to avoid nav2 build error
- ignore applying uncrustify to EigenLab.hpp because newer uncrustify format the code weirdly.

**Review by Ryanf55 — APPROVED** [review]
LGTM. I subscribed to the upstream PR. Is there another issue for octomap we can follow?

**Comment by wep21** [comment]
@Ryanf55 The new release of octomap_server is [ongoing](https://github.com/ros/rosdistro/pull/41344). Please wait for it and the next sync.

**Pull request merged**
