### PR TITLE
fix: build error on jammy

### PR DESCRIPTION
**Pull request by wep21**
fix build error as below on jammy
```
/usr/include/eigen3/Eigen/src/Core/functors/AssignmentFunctors.h:24:102: error: ‘outputColor.Eigen::Array<float, 3, 1, 0, 3, 1>::<unnamed>.Eigen::PlainObjectBase<Eigen::Array<float, 3, 1, 0, 3, 1> >::m_storage.Eigen::DenseStorage<float, 3, 3, 1, 0>::m_data.Eigen::internal::plain_array<float, 3, 0, 0>::array[2]’ may be used uninitialized [-Werror=maybe-uninitialized]
   24 |   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff(DstScalar& a, const SrcScalar& b) const { a = b; }
      |                                                                                                    ~~^~~
/home/daisuke/workspace/sandbox_ws/src/grid_map/grid_map_filters/src/ColorBlendingFilter.cpp: In member function ‘bool grid_map::ColorBlendingFilter<T>::update(const T&, T&) [with T = grid_map::GridMap]’:
/home/daisuke/workspace/sandbox_ws/src/grid_map/grid_map_filters/src/ColorBlendingFilter.cpp:117:56: note: ‘outputColor’ declared here
  117 |       Eigen::Array3f backgroundColor, foregroundColor, outputColor;
```

### CODE REVIEW

**Comment by wep21** [comment]
cc @SteveMacenski

**Comment by SteveMacenski** [comment]
I am not at the moment maintaining this package, the source has diverged so much since ROS 1 and has not been synced that I have stopped directly supporting this project until it becomes a Nav2 dependency or there are better version update policies.

**Comment by wep21** [comment]
@maximilianwulf Can I support the ros2 branch of this project instead of @SteveMacenski? Is it possible to give me the write access to this repository?

**Comment by wep21** [comment]
@maximilianwulf Thank you for your reply. First of all, I would like to release grid map to ros2 humble after navigation2 is released, so is it possible to give me the maintainer access right? After releasing, I would like to backport some features from ros1 branch.

**Comment by maximilianwulf** [comment]
Thank you. That would be great. I am checking with DevOps, but it should not be a problem.

**Comment by wep21** [comment]
@maximilianwulf Could you let me know when you're done checking with DevOps? I will make [this pr](https://github.com/ros2-gbp/ros2-gbp-github-org/pull/73) ready for review after that.

**Comment by maximilianwulf** [comment]
Done. Thank you for bringing the ROS2 topic forward. 

@SteveMacenski thank you also again for pushing it.

**Pull request merged**
