### PR TITLE
Add height of cluster with the most points method

### PR DESCRIPTION
**Pull request by kosuke55**
Thank you for the work.
I added the method to  use the mean value of the cluster with the most points as elevation value.
This method may be able to estimate more ground-like values.

0: Smallest value among the average values ​​of each cluster (current method)
Screenshot from 2021-09-08 20-51-47

1: Mean value of the cluster with the most points (new method)
(height_thresh is a parameter for this methods to reduce the influence of point clouds that exist in high locations such as ceilings.)
Screenshot from 2021-09-08 21-21-42

### CODE REVIEW

**Comment by kosuke55** [comment]
@pfankhauser 
Do you have any comment on my idea or could you please review?

**Comment by kosuke55** [comment]
ping @maximilianwulf  @SteveMacenski @Marwan99

**Comment by maximilianwulf** [comment]
Hey, could you retarget it to the main branch?

**Comment by kosuke55** [comment]
@maximilianwulf 
Do you mean not main but master?

**Comment by maximilianwulf** [comment]
Yes.

**Comment by kosuke55** [comment]
Yes. I'm working enterily with ROS2.

**Comment by maximilianwulf** [comment]
Could you in any case create a 2nd MR onto master?

**Comment by kosuke55** [comment]
OK, will you plan to review PR for master before this PR?

**Comment by kosuke55** [comment]
@maximilianwulf 
I created second PR for master https://github.com/ANYbotics/grid_map/pull/329.
Please check it.

**Comment by wep21** [comment]
friendly ping @maximilianwulf @SteveMacenski @Marwan99

**Comment by maximilianwulf** [comment]
Thank you.

**Pull request merged**
