### PR TITLE
Add Ryan as maintainer, remove Steve

### PR DESCRIPTION
**Pull request by Ryanf55**
Updating the list of maintainers to add myself and remove @SteveMacenski.

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]
Than you :heart: 

Oh, I didn't  realize you weren't on this already, yeah, this'll show you automatically CI build failures in the ROS buildfarm

**Comment by Ryanf55** [comment]
> Thank you ❤️
> 
> Oh, I didn't realize you weren't on this already, yeah, this'll show you automatically CI build failures in the ROS buildfarm

The code is perfect because CI is green here :stuck_out_tongue_winking_eye: 

@mergifyio backport iron
@mergifyio backport humble

**Comment by Ryanf55** [comment]
@Mergifyio backport iron

**Comment by Ryanf55** [comment]
@Mergifyio backport humble

**Pull request merged**
