### PR TITLE
Feature/enable octomap demo

### PR DESCRIPTION
**Pull request by wep21**
Resolves a part of #283.
Screenshot from 2022-01-06 23-27-55

### CODE REVIEW

**Comment by SteveMacenski** [comment]
You have a number of changes to the rviz configuration file that I don't think should be made. If there are some namespacing fixes, that's fine to fix, but we shouldn't be updating other unnecessary items

**Comment by SteveMacenski** [comment]
>   apt: command [apt-get install -y ros-rolling-octomap-ros] failed

CI failed, is this not released? We cannot do anything here until upstream is released.

**Comment by wep21** [comment]
> we shouldn't be updating other unnecessary items
@SteveMacenski added minimum changes for rviz config at https://github.com/ANYbotics/grid_map/pull/333/commits/2b46215a9f2d9715f68e9181b7630faa8fe30134.

**Comment by wep21** [comment]
> CI failed, is this not released? We cannot do anything here until upstream is released.

`octomap_ros` for `rolling` distro has not been released yet, so I added the missing dependency into repos file.

**Comment by wep21** [comment]
@SteveMacenski CI would be failed before merging this PR https://github.com/ANYbotics/grid_map/pull/332.

**Comment by SteveMacenski** [comment]
These are different failures directly related to your contribution of enabling octomap, no?

```Summary: 9 packages finished [14min 1s]
  1 package had stderr output: pcl_ros
executing command [apt-get install -y ros-rolling-octomap-rviz-plugins]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-rolling-octomap-rviz-plugins
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y ros-rolling-octomap-rviz-plugins] failed
```

**Comment by wep21** [comment]
> These are different failures directly related to your contribution of enabling octomap, no?

@SteveMacenski I'm sorry, I fixed the failure you suggested at https://github.com/ANYbotics/grid_map/pull/333/commits/6bcf5932821fc016c41bfad5e1950e9d739213df.

**Comment by wxmerkt** [comment]
`octomap_rviz_plugins` and `octomap_ros` have been released for Rolling - cf. https://github.com/ros/rosdistro/blob/baff070c4521611fb1e4e12d298fee3890c579b8/rolling/distribution.yaml#L2069-L2098

It's possible that they are only on the staging/testing server right now and not on the main synced one - so it depends which one the CI uses

**Comment by SteveMacenski** [comment]
We use the main rolling release, not testing/staging. I see there's an API deprecation issue here for CI passing around yaml, can you fix that? I'd like to see CI green to merge. I know its not something you did, but if you had a few minutes, I'd appreciate it.

**Comment by wep21** [comment]
@SteveMacenski Could you review #332, first? This PR fixes the ci failure. I will rebase after merging that.

**Comment by SteveMacenski** [comment]
OK

**Comment by wep21** [comment]
@SteveMacenski This is now green ci.

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Awesome! Thanks!

**Pull request merged**
