### PR TITLE
Rosbag timestamp changes.

### PR DESCRIPTION
**Pull request by rodericktaylor**
Didn't compile against rolling, had to change this to get it to compile.

### CODE REVIEW

**Comment by wep21** [comment]
@rodericktaylor There is another member named `recv_timestamp`. Is using `send_timestamp` here valid? cc @Ryanf55

**Review by wep21 — APPROVED** [review]
`send_timestamp` falls back to `recv_timestamp` when it's not available, so the change looks good.

**Review by Ryanf55 — APPROVED** [review]
LGTM. Rolling looks broken, but I'll merge this once I can figure out how to get it running again. Thanks for the contribution!

**Comment by wep21** [comment]
@rodericktaylor Thank you for your contribution. Your commit is merged in [another PR](https://github.com/ANYbotics/grid_map/pull/458). Is it alright to close this PR? cc @Ryanf55

**Comment by Ryanf55** [comment]
Closing.

**Pull request closed without merging**
