### PR TITLE
Restore ci setting for galactic

### PR DESCRIPTION
**Pull request by wep21**
This PR should be merged after
- docker image for `galactic` is ready. https://github.com/osrf/docker_images/pull/532
- `nav2_costmap_2d` is released for `galactic`

### CODE REVIEW

**Comment by wep21** [comment]
@SteveMacenski I appreciate if you could take a look at this PR.

**Comment by SteveMacenski** [comment]
You submitted this to the ros2 branch which was correctly already based on rolling as the master branch of this project for development in ros2, I'm not sure this is required.

**Comment by wep21** [comment]
I will change the target branch if you create `galactic-devel` branch.

**Comment by SteveMacenski** [comment]
We haven't done a release yet to make a galactic-specific branch worthwhile, we're still debating on the status of this project to release it. For now, I think this should be closed until such time a release is completed

**Comment by wep21** [comment]
I see. Could you tell me where the discussion is going on if it is open because I would like to catch up release status of this project?

**Pull request closed without merging**
