### PR TITLE
CI test PR 

### PR DESCRIPTION
**Pull request by Marwan99**

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Looks like you need some colcon ignores

**Comment by Marwan99** [comment]
There are in all non ported packages, just checked.

**Comment by SteveMacenski** [comment]
@Marwan99 https://github.com/ANYbotics/grid_map/tree/ros2/grid_map nope, the metapackage doesn't have it and that's who's trying to get it

**Comment by Marwan99** [comment]
My bad, I thought the ported packages were safe not to have `COLCON_IGNORE`.

**Pull request merged**
