### PR TITLE
Add colormaps for Rviz plugin

### PR DESCRIPTION
**Pull request by mmattamala**
Hi, I added support to colorize the grid map using some diverging and sequential [colormaps from matplotlib](https://matplotlib.org/stable/tutorials/colors/colormaps.html). I think it may be useful not only to make things nicer but also to highlight/debug easier.

### Main changes:
- It adds a new header `GridMapColorMaps.hpp` that includes the colormap tables. I have a Python script to generate more if required. It's not very elegant, but I wanted to avoid external dependencies.
- All references to `rainbow` in the code were changed to `colormap`. 
- The RViz plugin panel now adds an option to select the colormap.
image
- All the other options (scaling, inverting) work as before, but with more colors.

#### Coolwarm
coolwarm

#### Magma
magma

#### Spectral
spectral

#### Viridis (and inverted)
viridis
viridis_inverted

#### Rainbow (matplotlib version)
rainbow

#### and the infamous Jet
jet

### CODE REVIEW

**Comment by maximilianwulf** [comment]
Thank you very much. That definitely is very helpful. We will review and then merge it most probably.

**Comment by mmattamala** [comment]
Thanks @maximilianwulf 
Let me know if you have any comment or suggestions.

**Comment by Jaeyoung-Lim** [comment]
@mmattamala @maximilianwulf Is there any plans to getting this merged? This is a very useful feature to visualize different metrics / layers in the map

**Comment by mmattamala** [comment]
@Jaeyoung-Lim It is already merged :) https://github.com/ANYbotics/grid_map/commit/794909ade22c3dae1d10384c9417d3ba90979d8e

@maximilianwulf shall we close this PR then?

**Comment by maximilianwulf** [comment]
Yes, thank you for the contribution, we already merged this PR. 

The server does not automatically close PRs, so we have to do it manually.

**Comment by maximilianwulf** [comment]
@mmattamala thank you again, it is a great addition.

**Pull request closed without merging**
