### PR TITLE
[rolling] grid_map_pcl needs PCLConfig.cmake but not included in package.xml

### PR DESCRIPTION
**Pull request by kazuki0824**
In compile time, it needs PCLConfig.cmake for configuration, which is in libpcl-dev(in rosdep, it is defined as libpcl-all-dev)

On,
- Ubuntu 20.04
- Inside a Docker container Docker (ros:foxy)
- current HEAD on foxy_devel
,

I failed to build grid_map_pcl like below:

```
root@cb0f1bcd71a1:/_build_ws# colcon build
Starting >>> grid_map_cmake_helpers
--- stderr: grid_map_cmake_helpers
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "Findament_cmake_core.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ament_cmake_core", but CMake did not find one.

  Could not find a package configuration file provided by "ament_cmake_core"
  with any of the following names:

    ament_cmake_coreConfig.cmake
    ament_cmake_core-config.cmake

  Add the installation prefix of "ament_cmake_core" to CMAKE_PREFIX_PATH or
  set "ament_cmake_core_DIR" to a directory containing one of the above
  files.  If "ament_cmake_core" provides a separate development package or
  SDK, be sure it has been installed.


```

### CODE REVIEW

**Comment by kazuki0824** [comment]
Maybe this PR is subset of https://github.com/ANYbotics/grid_map/pull/245 ? Even if not, the topic seems related.

**Comment by kazuki0824** [comment]
Sure. There’s no problem to rebase it. Any actions for me to do?

**Comment by Ryanf55** [comment]
> Sure. There’s no problem to rebase it. Any actions for me to do?

Naw, just a rebase, and test it if you have time to make sure the key resolves in `rolling`. I'll be testing the change manually anyways for the time being because CI is broken. 
Thanks for the quick response.

**Comment by Ryanf55** [comment]
Looks like `rolling` already depends on the dev version of PCL, which is a bit overly bloated, but solves this issue. 
https://github.com/ANYbotics/grid_map/blob/886ba24724052cbb55e616ee36651a7fa07e9714/grid_map_pcl/package.xml#L24

A more optimal way to do dependencies is exactly what you did. I would be happy to accept this change in `rolling` which should reduce runtime dependency bloat.

**Comment by Ryanf55** [comment]
See #423 for a rebased and correct fix.

**Pull request closed without merging**
